# Generated by Django 5.0.6 on 2024-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_core", "0002_alter_markmodel_options_alter_usercar_mark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercar",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
